import ReactFlow, { Background, Controls, MiniMap } from "reactflow";

export default function DependencyGraph({ graph }) {
  if (!graph?.nodes?.length) return null;

  return (
    <section className="rounded-3xl border border-white/10 bg-zinc-900/70 p-6 backdrop-blur-xl">
      <div className="mb-4">
        <h2 className="text-xl font-bold text-white">Dependency Graph</h2>
        <p className="text-sm text-zinc-400">Visual codebase relationship map generated by ArcMind.</p>
      </div>

      <div className="h-[520px] overflow-hidden rounded-2xl border border-zinc-700 bg-zinc-950">
        <ReactFlow nodes={graph.nodes} edges={graph.edges} fitView>
          <MiniMap />
          <Controls />
          <Background />
        </ReactFlow>
      </div>
    </section>
  );
}